#!/usr/bin/env bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

git stash --keep-index -q

nix-build --no-build-output
RESULT=$?

git stash pop -q

exit $RESULT
